//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHospi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Diagonosticos = new HashSet<Diagonosticos>();
        }
    
        public int IdConsultas { get; set; }
        public Nullable<int> IdMedico { get; set; }
        public Nullable<int> IdArchivo { get; set; }
        public string Nombre { get; set; }
    
        public virtual Archivos Archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diagonosticos> Diagonosticos { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
